import type { ExecutionStep, ExecutionTrace, StackFrame, VisualizationOperation } from '@/types/execution';
import {
  parseJava,
  type ProgramNode,
  type ClassNode,
  type MethodNode,
  type ASTNode,
  type VarDeclNode,
  type AssignmentNode,
  type IfNode,
  type WhileNode,
  type ForNode,
  type ReturnNode,
  type BinaryExprNode,
  type MethodCallNode,
} from './javaParser';

class ReturnSignal {
  public value: any;
  constructor(value: any) {
    this.value = value;
  }
}

interface Scope {
  vars: Map<string, any>;
  parent?: Scope;
}

export class JavaInterpreter {
  private steps: ExecutionStep[] = [];
  private stepId = 0;
  private maxSteps = 1500;
  private globalScope: Scope = { vars: new Map() };
  private classes = new Map<string, ClassNode>();
  private methods = new Map<string, MethodNode>(); // "ClassName.methodName" or "methodName"
  private callStack: StackFrame[] = [];
  private mainArrayName: string | null = null;
  private mainArrayRef: number[] | null = null;
  private sortedIndices: number[] = [];

  private ast: ProgramNode;
  private sourceCode: string;

  constructor(ast: ProgramNode, sourceCode: string) {
    this.ast = ast;
    this.sourceCode = sourceCode;
    for (const cls of ast.classes) {
      this.classes.set(cls.name, cls);
      for (const m of cls.methods) {
        this.methods.set(`${cls.name}.${m.name}`, m);
        this.methods.set(m.name, m);
      }
    }
  }

  public run(): ExecutionTrace {
    this.steps = [];
    this.stepId = 0;
    this.callStack = [];
    this.mainArrayName = null;
    this.mainArrayRef = null;
    this.sortedIndices = [];

    // Find entry point: 'main' method or first method
    let entryMethod: MethodNode | null = null;
    let entryClass: ClassNode | null = null;

    for (const cls of this.ast.classes) {
      for (const m of cls.methods) {
        if (m.name === 'main' && m.isStatic) {
          entryMethod = m;
          entryClass = cls;
          break;
        }
      }
      if (entryMethod) break;
    }

    // If no main, find first non-main method
    if (!entryMethod && this.ast.classes.length > 0) {
      entryClass = this.ast.classes[0];
      entryMethod = entryClass.methods[0] || null;
    }

    if (!entryMethod || !entryClass) {
      throw new Error('No executable class or method found in Java code.');
    }

    // Execute entry method
    const scope: Scope = { vars: new Map(), parent: this.globalScope };
    this.callStack.push({
      functionName: `${entryClass.name}.${entryMethod.name}`,
      parameters: {},
      localVariables: {},
      lineNumber: entryMethod.line,
    });

    this.addStep(entryMethod.line, `Started ${entryClass.name}.${entryMethod.name}()`, []);

    try {
      this.executeBlock(entryMethod.body, scope);
    } catch (e) {
      if (!(e instanceof ReturnSignal)) {
        this.addStep(0, `❌ Runtime Error: ${(e as Error).message}`, []);
      }
    }

    if (this.callStack.length > 0) {
      this.callStack.pop();
    }

    // Mark sorted at finish if array is sorted
    const finalArr: number[] | null = this.mainArrayRef;
    if (finalArr && Array.isArray(finalArr) && this.isArraySorted(finalArr)) {
      const safeArr: number[] = finalArr;
      this.sortedIndices = safeArr.map((_: number, i: number) => i);
      this.addStep(0, `🎉 Array is fully sorted: [${safeArr.join(', ')}]`, []);
    }

    return {
      language: 'java',
      algorithmName: entryClass.name || 'Java Execution',
      code: this.sourceCode,
      steps: this.steps,
      totalSteps: this.steps.length,
      complexity: {
        time: 'O(n log n) / O(n²)',
        space: 'O(n) / O(1)',
        explanation: 'Automatic step trace generated by Java Virtual Execution Engine.',
      },
      description: `Execution trace of Java class ${entryClass.name}`,
    };
  }

  private isArraySorted(arr: number[]): boolean {
    for (let i = 0; i < arr.length - 1; i++) {
      if (arr[i] > arr[i + 1]) return false;
    }
    return true;
  }

  private getVariableSnapshots(scope: Scope): Record<string, any> {
    const vars: Record<string, any> = {};
    let curr: Scope | undefined = scope;

    while (curr) {
      for (const [key, val] of curr.vars.entries()) {
        if (!vars[key] && key !== 'this') {
          const type = Array.isArray(val) ? 'Array' : typeof val;
          const displayVal = Array.isArray(val) ? `[${val.join(', ')}]` : String(val);
          vars[key] = {
            name: key,
            value: displayVal,
            type,
            changed: true,
            scope: 'local',
          };
        }
      }
      curr = curr.parent;
    }
    return vars;
  }

  private getPointerLabels(scope: Scope): Record<string, number> {
    const pointers: Record<string, number> = {};
    if (!this.mainArrayRef) return pointers;

    const arrayLen = this.mainArrayRef.length;
    let curr: Scope | undefined = scope;

    // Track index-like variable names
    const indexNames = new Set(['i', 'j', 'k', 'l', 'r', 'm', 'left', 'right', 'mid', 'low', 'high', 'pivot', 'minIdx', 'min', 'target']);

    while (curr) {
      for (const [key, val] of curr.vars.entries()) {
        if (indexNames.has(key) && typeof val === 'number' && Number.isInteger(val)) {
          if (val >= 0 && val < arrayLen && pointers[key] === undefined) {
            pointers[key] = val;
          }
        }
      }
      curr = curr.parent;
    }

    return pointers;
  }

  private addStep(lineNumber: number, explanation: string, operations: VisualizationOperation[], scope?: Scope) {
    if (this.stepId >= this.maxSteps) return;

    const vars = scope ? this.getVariableSnapshots(scope) : {};
    const pointers = scope ? this.getPointerLabels(scope) : {};

    this.steps.push({
      id: this.stepId++,
      lineNumber: lineNumber || 0,
      explanation: explanation || '',
      variables: vars,
      stackFrames: [...this.callStack],
      heapObjects: [],
      operations: operations || [],
      arrayState: this.mainArrayRef ? [...this.mainArrayRef] : undefined,
      sortedIndices: [...this.sortedIndices],
      pointerLabels: pointers,
    });
  }

  private executeStatement(stmt: ASTNode, scope: Scope) {
    if (this.stepId >= this.maxSteps) return;

    switch (stmt.type) {
      case 'Block':
        this.executeBlock(stmt, scope);
        break;

      case 'VarDecl':
        this.executeVarDecl(stmt, scope);
        break;

      case 'Assignment':
        this.executeAssignment(stmt, scope);
        break;

      case 'If':
        this.executeIf(stmt, scope);
        break;

      case 'While':
        this.executeWhile(stmt, scope);
        break;

      case 'For':
        this.executeFor(stmt, scope);
        break;

      case 'Return':
        this.executeReturn(stmt, scope);
        break;

      case 'ExprStatement': {
        this.evaluateExpr(stmt.expr, scope);
        break;
      }
    }
  }

  private executeBlock(block: ASTNode & { statements: ASTNode[] }, scope: Scope) {
    const blockScope: Scope = { vars: new Map(), parent: scope };
    for (const s of block.statements) {
      this.executeStatement(s, blockScope);
    }
  }

  private executeVarDecl(stmt: VarDeclNode, scope: Scope) {
    for (const decl of stmt.declarations) {
      let initVal: any = decl.isArray ? [] : 0;
      if (decl.init) {
        initVal = this.evaluateExpr(decl.init, scope);
      }

      scope.vars.set(decl.name, initVal);

      // Detect if this is the main array to visualize
      if (Array.isArray(initVal) && (!this.mainArrayRef || decl.name === 'a' || decl.name === 'arr' || decl.name === 'nums')) {
        this.mainArrayName = decl.name;
        this.mainArrayRef = initVal;
        this.addStep(stmt.line, `Initialized array ${decl.name} = [${initVal.join(', ')}]`, [], scope);
      } else {
        const valStr = Array.isArray(initVal) ? `[${initVal.join(', ')}]` : String(initVal);
        this.addStep(stmt.line, `Declared ${stmt.varType} ${decl.name} = ${valStr}`, [], scope);
      }
    }
  }

  private executeAssignment(stmt: AssignmentNode, scope: Scope): any {
    const val = this.evaluateExpr(stmt.value, scope);

    if (stmt.target.type === 'Identifier') {
      const varName = stmt.target.name;
      this.setVariable(varName, val, scope);
      this.addStep(stmt.line, `Set ${varName} = ${val}`, [], scope);
    } else if (stmt.target.type === 'ArrayAccess') {
      const arr = this.evaluateExpr(stmt.target.array, scope);
      const index = this.evaluateExpr(stmt.target.index, scope);

      if (Array.isArray(arr)) {
        arr[index] = val;

        const isMainArray = arr === this.mainArrayRef;
        const targetName = isMainArray ? (this.mainArrayName || 'a') : 'subArray';

        this.addStep(
          stmt.line,
          `Set ${targetName}[${index}] = ${val}`,
          [{ type: 'ASSIGN', target: targetName, indices: isMainArray ? [index] : [] }],
          scope
        );
      }
    }
    return val;
  }

  private executeIf(stmt: IfNode, scope: Scope) {
    const cond = this.evaluateExpr(stmt.condition, scope);
    this.addStep(stmt.line, `Evaluating if condition (${Boolean(cond)})`, [], scope);

    if (cond) {
      this.executeStatement(stmt.thenBranch, scope);
    } else if (stmt.elseBranch) {
      this.executeStatement(stmt.elseBranch, scope);
    }
  }

  private executeWhile(stmt: WhileNode, scope: Scope) {
    let loopLimit = 0;
    while (Boolean(this.evaluateExpr(stmt.condition, scope)) && loopLimit < 500) {
      loopLimit++;
      this.executeStatement(stmt.body, scope);
      if (this.stepId >= this.maxSteps) break;
    }
  }

  private executeFor(stmt: ForNode, scope: Scope) {
    const forScope: Scope = { vars: new Map(), parent: scope };
    if (stmt.init) {
      this.executeStatement(stmt.init, forScope);
    }

    let loopLimit = 0;
    while (loopLimit < 500) {
      loopLimit++;
      if (stmt.condition) {
        const cond = this.evaluateExpr(stmt.condition, forScope);
        if (!cond) break;
      }

      this.executeStatement(stmt.body, forScope);

      if (stmt.update) {
        this.evaluateExpr(stmt.update, forScope);
      }

      if (this.stepId >= this.maxSteps) break;
    }
  }

  private executeReturn(stmt: ReturnNode, scope: Scope) {
    let val: any = undefined;
    if (stmt.value) {
      val = this.evaluateExpr(stmt.value, scope);
    }
    this.addStep(stmt.line, `Return ${val !== undefined ? val : ''}`, [], scope);
    throw new ReturnSignal(val);
  }

  private evaluateExpr(expr: ASTNode, scope: Scope): any {
    switch (expr.type) {
      case 'Assignment':
        return this.executeAssignment(expr, scope);

      case 'Literal':
        return expr.value;

      case 'Identifier':
        return this.getVariable(expr.name, scope);

      case 'ArrayLiteral':
        return expr.elements.map((el) => this.evaluateExpr(el, scope));

      case 'NewArray': {
        const size = Number(this.evaluateExpr(expr.size, scope));
        return new Array(Math.max(0, size)).fill(0);
      }

      case 'NewObject': {
        // Return dummy object
        return { __class: expr.className };
      }

      case 'ArrayAccess': {
        const arr = this.evaluateExpr(expr.array, scope);
        const index = this.evaluateExpr(expr.index, scope);
        if (Array.isArray(arr)) {
          return arr[index];
        }
        return undefined;
      }

      case 'MemberAccess': {
        const obj = this.evaluateExpr(expr.object, scope);
        if (Array.isArray(obj) && expr.property === 'length') {
          return obj.length;
        }
        if (obj && obj[expr.property] !== undefined) {
          return obj[expr.property];
        }
        return undefined;
      }

      case 'UnaryExpr': {
        if (expr.operator === '!') return !this.evaluateExpr(expr.argument, scope);
        if (expr.operator === '-') return -this.evaluateExpr(expr.argument, scope);
        if (expr.operator === '+') return +this.evaluateExpr(expr.argument, scope);

        if (expr.operator === '++' || expr.operator === '--') {
          if (expr.argument.type === 'Identifier') {
            const varName = expr.argument.name;
            const currVal = Number(this.getVariable(varName, scope));
            const newVal = expr.operator === '++' ? currVal + 1 : currVal - 1;
            this.setVariable(varName, newVal, scope);
            return expr.prefix ? newVal : currVal;
          }
        }
        return undefined;
      }

      case 'BinaryExpr': {
        const left = this.evaluateExpr(expr.left, scope);
        const right = this.evaluateExpr(expr.right, scope);

        // Auto-detect comparisons on array elements
        const isComparison = ['<', '<=', '>', '>=', '==', '!='].includes(expr.operator);
        if (isComparison && this.mainArrayRef) {
          this.recordArrayComparison(expr, left, right, scope);
        }

        switch (expr.operator) {
          case '+': return left + right;
          case '-': return left - right;
          case '*': return left * right;
          case '/': return Math.floor(left / right); // Java integer division
          case '%': return left % right;
          case '<': return left < right;
          case '<=': return left <= right;
          case '>': return left > right;
          case '>=': return left >= right;
          case '==': return left === right;
          case '!=': return left !== right;
          case '&&': return Boolean(left && right);
          case '||': return Boolean(left || right);
        }
        return undefined;
      }

      case 'MethodCall':
        return this.executeMethodCall(expr, scope);

      default:
        return undefined;
    }
  }

  private recordArrayComparison(expr: BinaryExprNode, leftVal: any, rightVal: any, scope: Scope) {
    let indices: number[] = [];

    // Check if left or right are array accesses on the main array
    if (expr.left.type === 'ArrayAccess') {
      const idx = this.evaluateExpr(expr.left.index, scope);
      if (typeof idx === 'number') indices.push(idx);
    }
    if (expr.right.type === 'ArrayAccess') {
      const idx = this.evaluateExpr(expr.right.index, scope);
      if (typeof idx === 'number') indices.push(idx);
    }

    if (indices.length > 0) {
      const targetName = this.mainArrayName || 'arr';
      this.addStep(
        expr.line,
        `Compare: ${leftVal} ${expr.operator} ${rightVal} (${leftVal <= rightVal})`,
        [{ type: 'COMPARE', target: targetName, indices }],
        scope
      );
    }
  }

  private executeMethodCall(call: MethodCallNode, scope: Scope): any {
    // Check for System.out.print / println
    let calleeName = '';
    if (call.callee.type === 'Identifier') {
      calleeName = call.callee.name;
    } else if (call.callee.type === 'MemberAccess') {
      calleeName = call.callee.property;
      if (call.callee.object.type === 'MemberAccess' && (call.callee.object as any).property === 'out') {
        // System.out.print(...)
        const printed = call.args.map((a) => this.evaluateExpr(a, scope)).join(' ');
        this.addStep(call.line, `[Output]: ${printed}`, [], scope);
        return undefined;
      }
    }

    const method = this.methods.get(calleeName);
    if (!method) return undefined;

    // Evaluate arguments
    const argValues = call.args.map((a) => this.evaluateExpr(a, scope));

    // Push Stack Frame
    const methodScope: Scope = { vars: new Map(), parent: this.globalScope };
    const paramsMap: Record<string, any> = {};

    method.params.forEach((param, i) => {
      const val = argValues[i];
      methodScope.vars.set(param.name, val);
      paramsMap[param.name] = val;

      // Track main array if passed as argument
      if (Array.isArray(val) && val.length > 0 && !this.mainArrayRef) {
        this.mainArrayName = param.name;
        this.mainArrayRef = val;
      }
    });

    const frame: StackFrame = {
      functionName: method.name,
      parameters: paramsMap,
      localVariables: {},
      lineNumber: method.line,
    };
    this.callStack.push(frame);

    const argsSummary = argValues.map((v) => (Array.isArray(v) ? `[${v.length} items]` : String(v))).join(', ');
    this.addStep(call.line, `Calling ${method.name}(${argsSummary})`, [], methodScope);

    let returnVal: any = undefined;
    try {
      this.executeBlock(method.body, methodScope);
    } catch (e) {
      if (e instanceof ReturnSignal) {
        returnVal = e.value;
      } else {
        throw e;
      }
    } finally {
      this.callStack.pop();
      this.addStep(call.line, `Returned from ${method.name}()`, [], scope);
    }

    return returnVal;
  }

  private getVariable(name: string, scope: Scope): any {
    let curr: Scope | undefined = scope;
    while (curr) {
      if (curr.vars.has(name)) {
        return curr.vars.get(name);
      }
      curr = curr.parent;
    }
    return undefined;
  }

  private setVariable(name: string, value: any, scope: Scope) {
    let curr: Scope | undefined = scope;
    while (curr) {
      if (curr.vars.has(name)) {
        curr.vars.set(name, value);
        return;
      }
      curr = curr.parent;
    }
    scope.vars.set(name, value);
  }
}

export function executeJavaCode(source: string): ExecutionTrace {
  const ast = parseJava(source);
  const interpreter = new JavaInterpreter(ast, source);
  return interpreter.run();
}
